### ISSUE TITLE
Add more evaluation criteria | Interface changes?

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/NiaARM#25]
The following evaluation criteria are currently included in this framework: support, confidence, shrinkage, coverage. However, some important indicators are still missing: 
- amplitude,
- comprehensibility,
- interestingness.

@zStupan we should support also these indicators (outlined also in [paper](https://arxiv.org/pdf/2010.15524.pdf)). Do you think we can provide simpler interface for adding criteria? User of this framework should have an option to select one or more criteria when preparing run script (option: supp and conf may not be mandatory). Fitness function should then be composed according to the selection of the user.

**Comment by firefly-cpp** [comment]
Each criterion should have also one corresponding weight (alpha, beta, gamma, etc.)

**Comment by zStupan** [comment]
@firefly-cpp For amplitude, I just ignore the categorical features, right?

**Comment by firefly-cpp** [comment]
Good idea @zStupan!

Yes. You can ignore it. It is very similar to shrinkage.

**Comment by firefly-cpp** [comment]
It would be nice to have also: lift, netconf and yulesq metric [(used in paper)](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8965539) implemented in this package.

**Comment by zStupan** [comment]
@firefly-cpp I'm almost done with this. I just have to incorporate all the metrics into the fitness evaluation, and then write some docs. 

There are a lot of metrics (10 currently), so it would probably be best to change the interface, as you've said. I suggest having a single parameter `metrics` in the NiaARM constructor which is either  a dict of `{'metric_name': metric_weight}` or a sequence (tuple or list) of strings i.e. metric names. In the latter case, the weights of the metrics in the sequence would be set to 1. In both cases the missing metrics' weights would be set to 0.

Also, there is a problem with calculating the fitness this way, with all these metrics, because Yule's Q is in the range [-1, 1] and lift is in the range [0, infinity], I believe. So if using those two metrics, the fitness value could become huge, potentially, and it won't be in [0, 1].

**Comment by firefly-cpp** [comment]
Good news, many thanks @zStupan! Yeah. I am aware of the problem.  Yule's Q and netconf can be used for statistical purpose for now. Most of the time, they are just part of statistical evaluation reported in the research papers.

**Comment by firefly-cpp** [comment]
Anyway, we may also think about the construction of new fitness functions.

**Comment by firefly-cpp** [comment]
[Conviction](https://en.wikipedia.org/wiki/Association_rule_learning#Conviction) is another metric that may be useful for this framework.
