### ISSUE TITLE
Test for text mining is missing

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/NiaARM#63]

**Comment by firefly-cpp** [comment]
@zStupan , what is the status of this issue?

**Comment by zStupan** [comment]
@firefly-cpp I am working on it currently.

**Comment by firefly-cpp** [comment]
Thanks for all the hard work, @zStupan

**Comment by zStupan** [comment]
@firefly-cpp no problem.

I'm not sure if our implementation of ARTM is correct, because it generates no rules sometimes. I am currently cross referencing the original paper's sources, trying to find more detailed descriptions of some of the methods used. Particularly, how the TF-IDF matrix was used to calculate support and confidence.
